package derigible.visual.main;

public enum Filter {
	CATEGORIES,
	ACCOUNTS,
	DATE,
	DATES,
	CATEGORIES_AND_DATE,
	CATEGORIES_AND_DATES,
	ACCOUNTS_AND_DATE,
	ACCOUNTS_AND_DATES,
	CATEGORIES_AND_ACCOUNTS_AND_DATE,
	CATEGORIES_AND_ACCOUNTS_AND_DATES
}
